import React, { useState, useEffect, useCallback } from 'react';
import { useParams } from 'react-router-dom';
import {
    PlusIcon,
    TrashIcon,
    ArrowDownTrayIcon,
    DocumentTextIcon,
    EyeIcon,
} from '@heroicons/react/24/outline';
import api from '../../lib/api';
import PermissionGate from '../components/PermissionGate';
import DataTable from '../components/DataTable';
import Modal from '../components/Modal';
import EmptyState from '../components/EmptyState';

const REPORT_TYPES = [
    { value: 'campaign_overview', label: 'Campaign Overview' },
    { value: 'voter_summary', label: 'Voter Summary' },
    { value: 'field_ops', label: 'Field Operations' },
    { value: 'finance', label: 'Finance' },
    { value: 'election_day', label: 'Election Day' },
    { value: 'strategy', label: 'Strategy & Messaging' },
];

export default function ReportsPage() {
    const { campaignId } = useParams();
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(true);
    const [typeFilter, setTypeFilter] = useState('');
    const [showGenerate, setShowGenerate] = useState(false);
    const [showView, setShowView] = useState(null);
    const [form, setForm] = useState({ type: 'campaign_overview', title: '', description: '' });
    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState(null);
    const [page, setPage] = useState(1);
    const [meta, setMeta] = useState({});

    const fetch = useCallback(async (pg = page) => {
        setLoading(true);
        try {
            const params = { page: pg };
            if (typeFilter) params.type = typeFilter;
            const { data } = await api.get(`/campaigns/${campaignId}/reports`, { params });
            setItems(data.data || []);
            setMeta(data.meta || { current_page: data.current_page, last_page: data.last_page, total: data.total });
        } catch { /* handled */ }
        setLoading(false);
    }, [campaignId, typeFilter, page]);

    useEffect(() => { fetch(); }, [fetch]);

    const handleGenerate = async (e) => {
        e.preventDefault();
        setSubmitting(true);
        setError(null);
        try {
            const { data } = await api.post(`/campaigns/${campaignId}/reports/generate`, form);
            setShowGenerate(false);
            setForm({ type: 'campaign_overview', title: '', description: '' });
            fetch();
            setShowView(data);
        } catch (err) {
            setError(err.response?.data?.message || 'Something went wrong.');
        }
        setSubmitting(false);
    };

    const handleExport = async (type) => {
        try {
            const { data } = await api.get(`/campaigns/${campaignId}/reports/export`, {
                params: { type },
                responseType: 'blob',
            });
            const url = window.URL.createObjectURL(new Blob([data]));
            const link = document.createElement('a');
            link.href = url;
            link.setAttribute('download', `${type}_report.csv`);
            document.body.appendChild(link);
            link.click();
            link.remove();
        } catch { /* handled */ }
    };

    const handleDelete = async (id) => {
        if (!window.confirm('Delete this report?')) return;
        try {
            await api.delete(`/campaigns/${campaignId}/reports/${id}`);
            fetch();
        } catch { /* handled */ }
    };

    const typeLabelMap = Object.fromEntries(REPORT_TYPES.map((t) => [t.value, t.label]));

    const columns = [
        { key: 'title', label: 'Title' },
        { key: 'type', label: 'Type', render: (row) => <span className="capitalize">{typeLabelMap[row.type] || row.type}</span> },
        { key: 'creator', label: 'Generated By', render: (row) => row.creator?.name || '' },
        { key: 'created_at', label: 'Date', render: (row) => row.created_at ? new Date(row.created_at).toLocaleDateString() : '' },
    ];

    const actions = (row) => (
        <div className="flex space-x-1">
            <button onClick={() => setShowView(row)} className="p-1 text-blue-600 hover:bg-blue-50 rounded" title="View"><EyeIcon className="h-4 w-4" /></button>
            <PermissionGate permission="reports.create">
                <button onClick={() => handleDelete(row.id)} className="p-1 text-red-600 hover:bg-red-50 rounded"><TrashIcon className="h-4 w-4" /></button>
            </PermissionGate>
        </div>
    );

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <h1 className="text-2xl font-heading font-bold text-gray-900">Reports</h1>
            </div>

            <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                    <select value={typeFilter} onChange={(e) => { setTypeFilter(e.target.value); setPage(1); }} className="border rounded-lg px-3 py-2 text-sm">
                        <option value="">All types</option>
                        {REPORT_TYPES.map((t) => <option key={t.value} value={t.value}>{t.label}</option>)}
                    </select>
                </div>
                <div className="flex items-center space-x-2">
                    <PermissionGate permission="reports.export">
                        <div className="relative group">
                            <button className="flex items-center space-x-1 border border-gray-300 text-gray-700 px-4 py-2 rounded-lg text-sm hover:bg-gray-50">
                                <ArrowDownTrayIcon className="h-4 w-4" /><span>Export CSV</span>
                            </button>
                            <div className="hidden group-hover:block absolute right-0 mt-1 w-48 bg-white border rounded-lg shadow-lg z-10">
                                {REPORT_TYPES.map((t) => (
                                    <button key={t.value} onClick={() => handleExport(t.value)} className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">
                                        {t.label}
                                    </button>
                                ))}
                            </div>
                        </div>
                    </PermissionGate>
                    <PermissionGate permission="reports.create">
                        <button onClick={() => setShowGenerate(true)} className="flex items-center space-x-1 bg-primary-600 text-white px-4 py-2 rounded-lg text-sm hover:bg-primary-700">
                            <PlusIcon className="h-4 w-4" /><span>Generate Report</span>
                        </button>
                    </PermissionGate>
                </div>
            </div>

            {items.length === 0 && !loading ? (
                <EmptyState icon={DocumentTextIcon} title="No reports yet" description="Generate your first report to see aggregated campaign data." />
            ) : (
                <DataTable columns={columns} data={items} loading={loading} actions={actions} meta={meta} onPageChange={(pg) => { setPage(pg); fetch(pg); }} />
            )}

            <Modal isOpen={showGenerate} onClose={() => setShowGenerate(false)} title="Generate Report">
                <form onSubmit={handleGenerate} className="space-y-4">
                    {error && <div className="text-red-600 text-sm">{error}</div>}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Report Type *</label>
                        <select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} className="w-full border rounded-lg px-3 py-2">
                            {REPORT_TYPES.map((t) => <option key={t.value} value={t.value}>{t.label}</option>)}
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Title</label>
                        <input type="text" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Auto-generated if empty" className="w-full border rounded-lg px-3 py-2" />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                        <textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={2} className="w-full border rounded-lg px-3 py-2" />
                    </div>
                    <div className="flex justify-end space-x-2">
                        <button type="button" onClick={() => setShowGenerate(false)} className="px-4 py-2 border rounded-lg text-sm">Cancel</button>
                        <button type="submit" disabled={submitting} className="px-4 py-2 bg-primary-600 text-white rounded-lg text-sm hover:bg-primary-700 disabled:opacity-50">{submitting ? 'Generating...' : 'Generate'}</button>
                    </div>
                </form>
            </Modal>

            <Modal isOpen={!!showView} onClose={() => setShowView(null)} title={showView?.title || 'Report'}>
                {showView && (
                    <div className="space-y-4">
                        <div className="flex items-center justify-between text-sm text-gray-500">
                            <span>{typeLabelMap[showView.type] || showView.type}</span>
                            <span>{showView.created_at ? new Date(showView.created_at).toLocaleString() : ''}</span>
                        </div>
                        {showView.description && <p className="text-sm text-gray-600">{showView.description}</p>}
                        <div className="bg-gray-50 rounded-lg p-4 overflow-auto max-h-96">
                            <ReportDataView type={showView.type} data={showView.data} />
                        </div>
                    </div>
                )}
            </Modal>
        </div>
    );
}

function ReportDataView({ type, data }) {
    if (!data) return <p className="text-gray-500">No data available.</p>;

    if (type === 'campaign_overview') {
        return (
            <div className="space-y-4">
                <Section title="Campaign">
                    <KV label="Name" value={data.campaign?.name} />
                    <KV label="Level" value={data.campaign?.level} />
                </Section>
                <Section title="Team">
                    <KV label="Total Members" value={data.team?.total_members} />
                    {data.team?.by_role && <RoleBreakdown roles={data.team.by_role} />}
                </Section>
                <Section title="Voters">
                    <KV label="Total" value={data.voters?.total} />
                    <KV label="Added (30d)" value={data.voters?.added_last_30_days} />
                </Section>
                <Section title="Finance">
                    <KV label="Budget" value={fmt(data.finance?.total_budget)} />
                    <KV label="Spent" value={fmt(data.finance?.total_spent)} />
                    <KV label="Donations" value={fmt(data.finance?.total_donations)} />
                </Section>
            </div>
        );
    }

    if (type === 'voter_summary') {
        return (
            <div className="space-y-3">
                <KV label="Total Voters" value={data.total} />
                <KV label="Added (30d)" value={data.added_last_30_days} />
                {data.by_status && <MapDisplay title="By Status" map={data.by_status} />}
                {data.by_ward && Object.keys(data.by_ward).length > 0 && <MapDisplay title="By Ward" map={data.by_ward} />}
            </div>
        );
    }

    if (type === 'finance') {
        return (
            <div className="space-y-3">
                <KV label="Total Budget" value={fmt(data.total_budget)} />
                <KV label="Total Spent" value={fmt(data.total_spent)} />
                <KV label="Remaining" value={fmt(data.budget_remaining)} />
                <KV label="Donations" value={fmt(data.total_donations)} />
                <KV label="Net Position" value={fmt(data.net_position)} />
            </div>
        );
    }

    if (type === 'election_day') {
        return (
            <div className="space-y-3">
                <KV label="Total Stations" value={data.stations?.total} />
                <KV label="Reported" value={data.stations?.reported} />
                <KV label="Votes Cast" value={data.votes?.total_cast} />
                <KV label="Turnout" value={`${data.votes?.turnout_percentage}%`} />
                {data.candidates?.length > 0 && (
                    <div>
                        <p className="text-sm font-medium mb-1">Candidates</p>
                        {data.candidates.map((c, i) => (
                            <div key={i} className="flex justify-between text-sm py-1">
                                <span>{c.candidate} ({c.party || '-'})</span>
                                <span className="font-bold">{c.total_votes?.toLocaleString()}</span>
                            </div>
                        ))}
                    </div>
                )}
                <KV label="Incidents" value={data.incidents?.total} />
                <KV label="Unresolved" value={data.incidents?.unresolved} />
            </div>
        );
    }

    return <pre className="text-xs whitespace-pre-wrap">{JSON.stringify(data, null, 2)}</pre>;
}

function Section({ title, children }) {
    return (
        <div>
            <h4 className="text-sm font-semibold text-gray-800 mb-2">{title}</h4>
            <div className="pl-2 space-y-1">{children}</div>
        </div>
    );
}

function KV({ label, value }) {
    return (
        <div className="flex justify-between text-sm">
            <span className="text-gray-500">{label}</span>
            <span className="font-medium">{value ?? '-'}</span>
        </div>
    );
}

function MapDisplay({ title, map }) {
    return (
        <div>
            <p className="text-sm font-medium mb-1">{title}</p>
            {Object.entries(map).map(([k, v]) => (
                <div key={k} className="flex justify-between text-sm py-0.5">
                    <span className="capitalize text-gray-500">{k}</span>
                    <span className="font-medium">{v}</span>
                </div>
            ))}
        </div>
    );
}

function RoleBreakdown({ roles }) {
    return (
        <div>
            <p className="text-sm font-medium mb-1">By Role</p>
            {Object.entries(roles).map(([role, count]) => (
                <div key={role} className="flex justify-between text-sm py-0.5">
                    <span className="text-gray-500">{role}</span>
                    <span className="font-medium">{count}</span>
                </div>
            ))}
        </div>
    );
}

function fmt(val) {
    if (val == null) return '-';
    return Number(val).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
